### ISSUE TITLE
Resize banner

### ISSUE THREAD

**Issue by Pouja** [danielcolon/ijzersterk#13]
This moment we kinda cropped the banner (the background of the navigation bar/menu).
It would be nice to adjust the banner in such way that is fully visible instead of cropped and that the sides can be filled with a black color.
Can you do this @danielcolon ? If you create the banner in such a way that I can fill the sides with black then I will place it on the website.

**Comment by danielcolon** [comment]
I like the banner as it is. It doesn't distract from the content of the page or the logo and menu.
Making it narrower artificially by fading to a solid color on the sides would look bad.
I would suggest closing this issue and maybe experimenting with a different photograph.

**Comment by Pouja** [comment]
I agree
