### ISSUE TITLE
Recreating boostrap calendar in react

### ISSUE THREAD

**Issue by Pouja** [danielcolon/ijzersterk#19]
Currently in the process of recreating the [boostrap-calendar](http://bootstrap-calendar.azurewebsites.net/) in React in the branch agenda. It was written in jQuery, so we have to rewrite it in React.

Currently todo:
- [x] When clicking on day in the month view, it should slide op the cal-slide-box
- [x] When hovering over an event, it should highlight the days the event is active
- [x] Create the day view
- [ ] Let AgendaEvents fetch the events from the server
- [ ] Make events CRUD
- [x] Make it visible, if any, which participants are going to that event.
- [x] Make a "I'm attending/leaving" button which adds/remove you from the participants of that event

@pevers can you help me with this if you are interested.

**Comment by pevers** [comment]
@Pouja Yes, I would like to help, atm I'm a little bit busy and I have almost 0 experience with React but I can learn ;)

**Comment by Pouja** [comment]
Nice! React is not that difficult, so you will be fine.

**Comment by Pouja** [comment]
Closing in favor of facebook events or teamstuff
