### ISSUE TITLE
Separating frontend backend

### ISSUE THREAD

**Issue by Pouja** [danielcolon/ijzersterk#22]
Maybe we should create 2 repos. 1 for the backend. And 1 for the frontend.

**Comment by danielcolon** [comment]
But why? Seems to me that it'd just be more of a hassle and we'd have to migrate.
If you  wo I'm fine with it I just don't really see the benefits

**Comment by Pouja** [comment]
Because the front-end and back-end are 2 separate entities that are independent of each other, so it made more sense to have 2 repos as well. They also have different releases (tags), issues, commits and pull requests.

**Comment by Pouja** [comment]
Done
