### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Pouja** [danielcolon/ijzersterk#24]
There is currently no login nor CRUD of the users in the frontend.
- [ ] Login in
- [ ] Show all the users (admin)
- [ ] Delete and create users (admin)
- [ ] Forgot password (normal user) and reset password (admin)

**Comment by danielcolon** [comment]
I can implement a forgot password. I thought it might be more secure to only give admins the possibility to change a users's password. This should be manageable in a small group like ours

**Comment by Pouja** [comment]
Closed, see https://github.com/Ijzersterk/frontend/issues/1
