### ISSUE TITLE
Fetching images

### ISSUE THREAD

**Issue by Pouja** [danielcolon/ijzersterk#25]
Currently all the images are hardcoded to the old website in the new one.
There should be something like fetching all the images that there are with a matching directory.

**Comment by danielcolon** [comment]
You'd like an endpoint that would return a list of images available? Does it need other properties like size, orientation, title etc?

**Comment by Pouja** [comment]
Hmm that is sounds to good to have those properties as well, but for now not really necessary. Only need to know to which directory/category an image belongs to.

**Comment by Pouja** [comment]
Continuing in https://github.com/Ijzersterk/api/issues/1
