### ISSUE TITLE
Teamstuff

### ISSUE THREAD

**Issue by Pouja** [danielcolon/ijzersterk#32]
So there is a website called [teamstuff](http://www.teamstuff.com) where you can register a team and plan in training and competition.  
All members of the team (in our case that would be all dskv ijzersterk members) can say that they would attend or not. Plus the making of the events are quite well made.  

So do we want to use that instead of this calendar system? For now, we can definitely use teamstuff and continue working on this. Or we can say that we are completely stopping with this in favour of teamstuff.

A little pro and con comparison

Pro using Calendar we are currently developing:
- We can add missing feature ourself which teamstuff does not have (for example comments on events)
- We can customize it any time we want
- Integrate maybe with weightxreps.com and our #31 

Con
- Requires significant time to develop this (finish it, make it work on mobile nicely, testing, adding mailing notification etc..)
- Kinda reinventing the wheel (although teamstuff is not completely made for organisation like us)

What do you say @danielcolon and @pevers

**Comment by pevers** [comment]
@Pouja Let's give it a try, if it is too cumbersome we can develop our own system!

**Comment by Pouja** [comment]
Closed, if any new discussing is wanted, do that at Ijzersterk/frontend or Ijzersterk/api
