### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by pevers** [danielcolon/ijzersterk#33]
I investigated some of the possibilities of a full featured blog.

**Ghost Platform (https://ghost.org/download/)**
This thing is getting quite popular in the Node community.
- Pros:
  - Very easy setup
  - Support for adding new users
  - Tweet, comment etc. on blogs
  - Support for designing our own template
  - Very fast
- Con:
  - Need to run a seperate Node server
  - If we would do this, we could run the blog on a seperate subdomain and create a template that looks like the website (I know, sounds ugly but it is easy). Or we integrate the build cycle with the current frontend cycle. 

After typing this I think this sucks, best option is to integrate but then we are forces to use EmberJS and all the stuff Ghost uses in their build cycle. 

**Writing own blog system**
Get a markdown parser, add support for images etc., is a lot of work but sounds fun. I think the blogs need to be fixed pretty quick so I will do this after implementing a 'temporary' option.

**Wordpress**
Wordpress is slow, all versions are vulnerable to hacks but it is easy to use and the server is already running php. Integrating this in the current website isn't that hard I think. I'm playing with this right now and I think I'm going for this option.

@Pouja @danielcolon

**Comment by Pouja** [comment]
Assume we drop the PHP, what will you suggest then?

**Comment by Pouja** [comment]
Btw we have moved to https://github.com/Ijzersterk/frontend So can you please move this issue as well to there?
