### ISSUE TITLE
Calendar is undocumented

### ISSUE THREAD

**Issue by danielcolon** [danielcolon/ijzersterk#9]
curl --user testuser:testpassword -H "Content-application/json" -X GET api.ijzersterkdelft.nl/calendar/
"{\"status\":\"200 OK\",\"details\":\"calendar returned\",\"result\":[\"1\",\"2\"]}"

curl --user testuser:testpassword -H "Content-application/json" -X GET api.ijzersterkdelft.nl/calendar/1
"{\"status\":\"200 OK\",\"details\":\"calendarEvent returned\",\"result\":{\"id\":\"1\",\"title\":\"Birth of the calendar\",\"description\":\"This event hallmarks the birth of the first calendarEvent\",\"start\":{\"date\":\"2015-08-03 18:30:00.000000\",\"timezone_type\":3,\"timezone\":\"Europe\\/Amsterdam\"},\"end\":{\"date\":\"2015-08-03 19:00:00.000000\",\"timezone_type\":3,\"timezone\":\"Europe\\/Amsterdam\"},\"viewlevel\":\"0\",\"editlevel\":\"2\"}}"

Dit nog documenteren. Nu even hier voor @Pouja

**Comment by Pouja** [comment]
The ISO format of time also includes the time zone, so please use the ISO format of time.
Also... we didn't even discuss which type of events in the calendar we can have or how we want to design it. So it seems like bad idea to start implementing it without defining the calendar with events.

**Comment by Pouja** [comment]
Also, either stick to dutch or to english. But dont mix them together :P

**Comment by danielcolon** [comment]
Timezone:
\"timezone_type\":3,\"timezone\":\"Europe\/Amsterdam
It's right there.

And yes my bad, switching a lot haha.

As for the premature implementation.
I thought a calendar should be simple. List of events with a start datetime and end datetime. Did you have something else in mind?

**Comment by Pouja** [comment]
What am I saying is that you can reduce the number of attributes by using the iso format of time to include "timezone_type" in it.

Well there are some points to discuss or to think about before we start implementing the calendar:
1. _Fist we have to know what "events" are in our domain. With that we can specify which type of events we can expect._
Well the types we can expect are: seminars, group training, vkr training, first year weekend etc. We should think which types we can expect besides the one that I just mentioned.
2. _Will all events be time constricted, or will they be day constricted. What if we have events which can cover multiple days (for example first year weekend)?_ Well it makes most sense to just have a start time and end time in ISO 8601 format. With that we cover all of them.
3. _Do we even want that people can comment on events? Also will the comments be CRUD then?_ This can be something in the future if people are interested. But I dont think that will be used then.
4. _Does a person comment that he wants to participate? Or will there be a "i will be there" button? If so, do we need that the user can provide additional information on that event participation? If so, what kinda information?_ Each events should also have 0 or more participants, where the use can join or leave an event. Also when the user wants to participate he/she can provide extra information. For example, if we have a "training" event, someone wants to participate and state that he/she will do chest or will be available for questions during the training etc.
5. _Can an event also have a static html page? Or will we just display some small information under it?_ I think that each event should have a title, small description and an optional link to the static html page within the website which tells more about the information. Or should we just create a "blog" for it? And reference it in the small description of the event?

**Comment by danielcolon** [comment]
All calendar times now in ISO-8601 31c5cbb7e850ca2c744f70bc51cb20273fcf1016
